import { useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { selectItems, clearCart } from "../slices/cartSlice";
import CheckoutProduct from "../components/CheckOutProduct";
import { useNavigate } from "react-router-dom";

// Utility function to load the Razorpay script dynamically
const loadScript = (src) => {
  return new Promise((resolve) => {
    const script = document.createElement("script");
    script.src = src;
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.body.appendChild(script);
  });
};

function Checkout() {
  const items = useSelector(selectItems);
  const dispatch = useDispatch();
  const navigate = useNavigate();
  
  const [email, setEmail] = useState("");
  const total = items.reduce((sum, item) => sum + item.price, 0);

  const handleCheckout = async () => {
    if (!email) {
      alert("Please enter an email address to receive your receipt.");
      return;
    }

    // 1. Load the Razorpay SDK
    const res = await loadScript("https://checkout.razorpay.com/v1/checkout.js");
    if (!res) {
      alert("Razorpay SDK failed to load. Are you online?");
      return;
    }

    const checkoutData = {
      items: items.map(item => ({ id: item.id, price: item.price })),
      total_amount: total,
      email: email
    };

    try {
      // 2. Ask backend to create a Razorpay Order
      const orderResponse = await fetch("https://ecommerce-clone-vp2h.onrender.com/api/razorpay/create_order", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(checkoutData),
      });
      
      const orderData = await orderResponse.json();
      
      if (!orderResponse.ok) {
        alert("Failed to create Razorpay order.");
        return;
      }

      // 3. Configure the Razorpay Popup
      const options = {
        key: "rzp_test_TJll7YzssBvYZ6", // Your Razorpay Test Key
        amount: total * 100, // Amount in paise
        currency: "INR",
        name: "dummy.zon",
        description: "Test Transaction",
        order_id: orderData.order_id, // The order ID generated by backend
        
        // This handler runs automatically when the payment is successful
        handler: async function (response) {
          // 4. Send the success details to your new verify route
          const verificationData = {
            razorpay_order_id: response.razorpay_order_id,
            razorpay_payment_id: response.razorpay_payment_id,
            razorpay_signature: response.razorpay_signature,
            items: checkoutData.items,
            total_amount: checkoutData.total_amount,
            email: checkoutData.email
          };

          const verifyResponse = await fetch("https://ecommerce-clone-vp2h.onrender.com/api/checkout/verify", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(verificationData),
          });

          if (verifyResponse.ok) {
            const verifyResult = await verifyResponse.json();
            alert(`Payment Successful! ${verifyResult.message}\nOrder ID: ${verifyResult.order_id}`);
            
            // Clear cart and redirect
            dispatch(clearCart());
            navigate("/");
          } else {
            alert("Payment verification failed. Please contact support.");
          }
        },
        prefill: {
          email: email,
        },
        theme: {
          color: "#FBBF24", // Amazon/dummy.zon yellow
        },
      };

      // 5. Open the Razorpay Popup
      const paymentObject = new window.Razorpay(options);
      paymentObject.open();

    } catch (error) {
      console.error("Checkout failed:", error);
      alert("Something went wrong during checkout.");
    }
  };

  return (
    <div className="lg:flex max-w-screen-2xl mx-auto p-4 gap-4">
      <div className="flex-grow m-2 shadow-sm">
        <div className="flex flex-col p-5 space-y-10 bg-white">
          <h1 className="text-3xl border-b pb-4 font-semibold">
            {items.length === 0 ? "Your dummy.zon Cart is empty." : "Shopping Cart"}
          </h1>
          {items.map((item, index) => (
            <CheckoutProduct key={index} id={item.id} title={item.title} price={item.price} description={item.description} category={item.category} image={item.image} />
          ))}
        </div>
      </div>

      {items.length > 0 && (
        <div className="flex flex-col bg-white p-6 shadow-md md:min-w-[300px] h-min mt-2">
          <h2 className="whitespace-nowrap font-medium text-lg mb-4">
            Subtotal ({items.length} items): 
            <span className="font-bold ml-2">${total.toFixed(2)}</span>
          </h2>

          <input 
            type="email"
            placeholder="Enter email for receipt"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="mb-4 p-2 border border-gray-300 rounded focus:outline-none focus:border-yellow-500"
            required
          />

          <button 
            onClick={handleCheckout} 
            className="p-2 w-full text-sm bg-gradient-to-b from-yellow-200 to-yellow-400 border border-yellow-300 rounded-sm hover:from-yellow-300 hover:to-yellow-500 active:from-yellow-400 active:to-yellow-500 focus:outline-none cursor-pointer"
          >
            Pay with Razorpay
          </button>
        </div>
      )}
    </div>
  );
}

export default Checkout;